### ISSUE TITLE
Discourse version compatibility?

### ISSUE THREAD

**Issue by mgaudet** [noahgibbs/rails_ruby_bench#1]
I'm playing around with this a bit, and am wondering what the expected support of various discourse versions is.

Because the Ruby+OMR preview is targeting Ruby 2.4 right now, I can't run Discourse v1.5.0 which is the tag you've got baked into the image

I've got marginal amounts of luck running Friday's master (20778fb), with the startup tests, but it blows up when running the load test: 

```
Running start-time benchmarks for 2 iterations...
Server is started, running start/stop iteration...
In PID 29510, starting server on port 4567
[29510] Puma starting in cluster mode...
[29510] * Version 3.6.0 (ruby 2.4.0-p0), codename: Sleepy Sunday Serenity
[29510] * Min threads: 0, max threads: 1
[29510] * Environment: development
[29510] * Process workers: 1
[29510] * Phased restart available
[29510] * Listening on tcp://0.0.0.0:4567
[29510] Use Ctrl-C to stop
[29510] - Worker 0 (pid: 29574) booted, phase: 0
server_stop: Interrupted Rails server at expected PID 29510.
Waiting for dead PID expecting 29510
[29510] - Gracefully shutting down workers...
[29510] === puma shutdown: 2017-04-24 11:34:58 -0400 ===
[29510] - Goodbye!
Got dead pid: 29510
Server is started, running start/stop iteration...
In PID 29600, starting server on port 4567
[29600] Puma starting in cluster mode...
[29600] * Version 3.6.0 (ruby 2.4.0-p0), codename: Sleepy Sunday Serenity
[29600] * Min threads: 0, max threads: 1
[29600] * Environment: development
[29600] * Process workers: 1
[29600] * Phased restart available
[29600] * Listening on tcp://0.0.0.0:4567
[29600] Use Ctrl-C to stop
[29600] - Worker 0 (pid: 29669) booted, phase: 0
server_stop: Interrupted Rails server at expected PID 29600.
Waiting for dead PID expecting 29600
[29600] - Gracefully shutting down workers...
[29600] === puma shutdown: 2017-04-24 11:35:04 -0400 ===
[29600] - Goodbye!
Got dead pid: 29600
In PID 29696, starting server on port 4567
[29696] Puma starting in cluster mode...
[29696] * Version 3.6.0 (ruby 2.4.0-p0), codename: Sleepy Sunday Serenity
[29696] * Min threads: 0, max threads: 1
[29696] * Environment: development
[29696] * Process workers: 1
[29696] * Phased restart available
[29696] * Listening on tcp://0.0.0.0:4567
[29696] Use Ctrl-C to stop
[29696] - Worker 0 (pid: 29767) booted, phase: 0
[29391]: Simulating activity for user id -1: system
[29391]: Getting Rails CSRF token...
[29391]: Logging in as "system"... (not part of benchmark request time(s))
Exception in worker thread: 403 Forbidden
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/2.4.0/net/http.rb:877:in `start'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:53:in `request'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:78:in `action_from_args'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:147:in `block in time_actions'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `each'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `time_actions'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:170:in `block (2 levels) in multithreaded_actions'
server_stop: Interrupted Rails server at expected PID 29696.
Waiting for dead PID expecting 29696
[29696] - Gracefully shutting down workers...
[29696] === puma shutdown: 2017-04-24 11:35:11 -0400 ===
[29696] - Goodbye!
Got dead pid: 29696
/home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 403 Forbidden (RestClient::Forbidden)
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /home/magaudet/.rbenv/versions/async_comp/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:53:in `request'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:78:in `action_from_args'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:147:in `block in time_actions'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `each'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `time_actions'
	from /home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:170:in `block (2 levels) in multithreaded_actions'
```
The question from me is: "Is this a problem where discourse is too new for the user simulator"?

**Comment by noahgibbs** [comment]
I actually haven't seen this 403 before, though there are definitely some cases where Discourse is too new. I was using head-of-master Discourse until recently (around three weeks ago), but they could easily have changed something important in the most recent round of 2.4-compatibility changes.

I'll try this out later today or tomorrow and see if I see the same thing with MRI 2.4.0 and latest Discourse.

Re: Discourse version: I've been handling this by making it easy to bake an image with a specific Discourse version (see packer/ami.json). But it could definitely make sense to make it easier to switch versions later.

On a booted image, in ~ubuntu/rails_ruby_bench/work/discourse you can also run Git commands to switch versions - it doesn't change the version after the AMI bake, so if you do, it'll keep your changes. So it'd definitely be possible to *add* some kind of runtime mechanism where start.rb checked out the appropriate Discourse version (or it could remain manual.)

**Comment by mgaudet** [comment]
I've been trying to use this locally (partially to give it a sniff test, partially because if the JIT crashes, I want to be able to problem determination). 

Seems something is up with the login-as-`system` step, but, I could have also goofed the setup, as I've done most of the discourse setup manually.

**Comment by noahgibbs** [comment]
There are some definite oddities in things like how it sets up seed/test data. I don't usually run it locally, partly for that reason.

**Comment by noahgibbs** [comment]
I'm seeing the same 403s with latest Discourse and Ruby 2.4.1 (Discourse doesn't work with latest-latest Ruby, but does with 2.4.1). Tracking it down now.

**Comment by noahgibbs** [comment]
Okay -- looks like the 1.8.0.betaX series has the problem with 403s, but is also the only Discourse with Ruby 2.4.0 compatibility. I assume they've changed something in either authentication or the URLs (still investigating why.)

It's hard to check because asset precompilation was broken for a lot of the older 1.8.0 betas, so there's a huge chunk of revisions in the middle that doesn't work -- hard to do a "git bisect" or equivalent.

They also have the 1.7.8 release, which is quite recent, but it doesn't seem to have the 2.4.0 compatibility -- or the 403s. So the 403 errors aren't due to an older Discourse URL change, it's something in the 1.8.0 beta series.

I'll keep investigating. But I don't see a 2.4.0-compatible version of Discourse that doesn't get the 403s, so for right now it's broken. I'll know later if it's broken because URLs changed (adds complexity to write a single benchmark compatible with both old and new Discourse) or because something's busted and they haven't fixed it yet (probably just a fix to Discourse.)

**Comment by noahgibbs** [comment]
Can repro this locally, and it's getting a valid-looking CSRF token from the CSRF route. If I use exactly one request (no warmup) it works intermittently, maybe 50% or so of the time. I thought maybe the CSRF tokens were changing more often and being checked? But no, if it doesn't even work reliably on a single request, that's something different. I'll check my cookie handling next. Maybe my user simulator isn't acting enough like a single-user session?

**Comment by noahgibbs** [comment]
Nope, I'm keeping the cookies continuously. Nothing has changed in how I'm doing that, and it seems like the obvious way to do it "right". As a workaround, I'll see about turning off CSRF protection in Discourse for the benchmark -- it's not perfect, but it should work. The CSRF line in Discourse's application_controller.rb hasn't changed since the very initial release of Discourse. So I have no clue why it stopped working, but I shouldn't have to worry about it changing soon.

**Comment by noahgibbs** [comment]
Okay, current versions turn off CSRF and work fine. I'll look into the CSRF problems later, but that's less urgent now. It works.
