### ISSUE TITLE
Having trouble setting up the benchmark

### ISSUE THREAD

**Issue by yimin-zhao** [noahgibbs/rails_ruby_bench#12]
Hi, I am doing statistics work(specially, hash table size information), I want to collect some real data from a real app but got some trouble in setting up this framework.
Can you do me a favor to see what's wrong?
The log messages are very long, so I uploaded it as a file
[rails_bench.txt](https://github.com/noahgibbs/rails_ruby_bench/files/2184705/rails_bench.txt)

Environment:
- ruby version:
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
- postgreSQL:
`psql (PostgreSQL) 9.6.9`
- Redis:
`Redis server v=4.0.10 sha=574d4472:0 malloc=jemalloc-4.0.3 bits=64 build=cb9a9f99a12b60ef`
- discourse:
at branch 1.8.0

Thanks~

**Comment by noahgibbs** [comment]
I've seen that error with the symlinks before, but only when trying to use more recent Discourse. Is it possible you changed/updated the Discourse version?

**Comment by yimin-zhao** [comment]
At first, I was using the head code, then I checkout to branch 1.8.0 (as well as 1.8.1, 1.8.2), the errors with symlinks doesn't disappear. I noticed that you suggest that discourse is at least version 1.8. But thanks for the hint, I will look deep into the code again.

**Comment by yimin-zhao** [comment]
Hi, I am wondering usually how long will it take for one full benchmark?

**Comment by noahgibbs** [comment]
"One full benchmark" in the sense of between 4,000 and 10,000 requests is around a minute or two. I often run them in batches of tens or hundreds, which takes longer. Above about 1,000 requests it's pretty linear -- 10x as many requests just takes 10x as long.

**Comment by yimin-zhao** [comment]
Hi, finally, I ran through all the code, here I want to record all the errors I encountered along with it's solution.

1. `failed to create symbolic link '/path/rails_ruby_bench/work/discourse/public/plugins/discourse-narrative-bot/public': File exists (RuntimeError)`

This is a weird one, I feel like it is the issue of concurrency, I tried mutex to lock the code but it can only reduce the errors and can't eliminate the errors. This one actually does not affect the benchmark, for me, I comment out the related code.

2. `Exception in worker thread: could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)`

The database thread pool is too small compare the worker number, I solve it by change the `pool` value to `20` in config/database.yml

3. `'fetch': key not found: :ciphers`

Upgrading rest-client to version 2.x, I don't know why my rest-client version in Gemfile.lock was set to 1.8.0

4. `500 Internal Server Error (RestClient::InternalServerError)`

The default worker number is set to 30 which is too much, after all my CPU is i5 with 4 cores.

5. stuck at the end of the script.
At line 411 - 412 in start.rb, 
```
"ec2 instance id" => `wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`,
    "ec2 instance type" => `wget -q -O - http://169.254.169.254/latest/meta-data/instance-type`
```
I can't open this links, @noahgibbs maybe you can check the validation of those links.

Thanks

**Comment by noahgibbs** [comment]
Those links won't be valid on your laptop. They're AWS links which check the AWS instance ID and type and record it. They should be harmless if you're not on AWS, and the backticks will return the empty string.
