### ISSUE TITLE
Running the Benchmark Locally: Steps don't work 

### ISSUE THREAD

**Issue by etagwerker** [noahgibbs/rails_ruby_bench#14]
Hey @noahgibbs, 

I love this project, great work! 😄 

I recently cloned the repo and found that the steps in the README don't work: 

```
$ bundle

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /Users/etagwerker/Projects/fastruby/rails_ruby_bench/work/discourse/Gemfile. Bundler cannot continue.
. Bundler cannot continue.

 #  from /Users/etagwerker/Projects/fastruby/rails_ruby_bench/Gemfile:6
 #  -------------------------------------------
 #
 >  eval_gemfile 'work/discourse/Gemfile'
 #  -------------------------------------------
```

It seems that the steps are out of order. I can submit a PR to address this issue. 

Just thought you should know.

Thanks!

**Comment by noahgibbs** [comment]
That would be lovely. I need to rework how this works locally in general - it's hard to use that way. But any improvement in the mean time would be appreciated :-)
